### ISSUE TITLE
Problems with database creation

### ISSUE THREAD

**Issue by uzun-masha** [davidemms/SHOOT#2]
Hi David!

I'm trying to run python create_shoot_db.py command to my local data. The code looks like this:
python create_shoot_db.py /mnt/c/Users/uzunm/mydata/OrthoFinder/Results_Mar30_5/
I got the comment "Args: input_directory [full,profiles]."
What does it mean? How can I fix this? OrthoFinder directory contains many subdirectories. Should I give the path to the entire directory or to a specific subdirectory?

Kind regards,
Maria

**Comment by davidemms** [comment]
Hi Maria

The "full" and "profiles" options should be explained in the paper, basically it's whether you want an orthogroup to be represented by all is members in the diamond database (full) or just selected representatives (profile). I'd recommend trying full to start with.

Best wishes
David

**Comment by uzun-masha** [comment]
Dear David,
Thanks a lot for your quick answer. I think I understood this step.
Next, I ran python shoot /mnt/c/Users/uzunm/Dropbox/elusi/ntr/OrthoFinder/Results_Mar31/spr.fasta /mnt/c/Users/uzunm/Dropbox/elusi/ntr/OrthoFinder/Results_Mar31/
and got the following error
Traceback (most recent call last):
  File "/home/uzun/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/uzun/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/uzunm/Dropbox/elusi/SHOOT-master/shoot/__main__.py", line 296, in <module>
    main(db, args.infile, opts)
  File "/mnt/c/Users/uzunm/Dropbox/elusi/SHOOT-master/shoot/__main__.py", line 72, in main
    ogs, scores = og_assign.assign(fn_for_use, q_ultra_sens=opts.search_high_sens)
  File "/mnt/c/Users/uzunm/Dropbox/elusi/SHOOT-master/shoot/og_assigner.py", line 53, in assign
    ogs, scores = self.og_from_diamond_results(fn_results)
  File "/mnt/c/Users/uzunm/Dropbox/elusi/SHOOT-master/shoot/og_assigner.py", line 92, in og_from_diamond_results
    with gzip.open(fn_og_results_out, 'rt') as infile:
  File "/home/uzun/miniconda3/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/uzun/miniconda3/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/uzunm/Dropbox/elusi/ntr/OrthoFinder/Results_Mar31/spr.fasta.sh.ogs.txt.gz'

Also then i ran python test_msa_grafter_epa.py I got the following error
no custom django settings found, using defaults..
No custom context found, using defaults...
Traceback (most recent call last):
  File "test_msa_grafter_epa.py", line 11, in <module>
    from shoot import msa_grafter_epa as mg
ImportError: cannot import name 'msa_grafter_epa' from 'shoot' (/home/uzun/miniconda3/lib/python3.8/site-packages/shoot/__init__.py)

and for python test_utils.py it is the same mistake.
Can you please help me to solve this?

Best wishes,
Maria

**Comment by LDoni** [comment]
Hello 
I have exactly the same error
@uzun-masha did you solve the problem?
Thanks
L

**Comment by uzun-masha** [comment]
@Luponsky no, I used local BLAST and constructed phylogenetic trees to find needed orthologous groups.
