### ISSUE TITLE
Problem running shoot "No such file or directory: '.sh.ogs.txt.gz'"

### ISSUE THREAD

**Issue by nkaml** [davidemms/SHOOT#3]
when I run: python shoot candidate_sequences.fasta OrthoFinder/Results_Mar28/diamond_all_sequences.subtrees.fa
I get the following error
Traceback (most recent call last):
  File "/home/........./envs/orthofinder/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home//........./anaconda3/envs/orthofinder/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home//........./tools/SHOOT/shoot/__main__.py", line 296, in <module>
    main(db, args.infile, opts)
  File "/home/........./tools/SHOOT/shoot/__main__.py", line 72, in main
    ogs, scores = og_assign.assign(fn_for_use, q_ultra_sens=opts.search_high_sens)
  File "/home/........./tools/SHOOT/shoot/og_assigner.py", line 53, in assign
    ogs, scores = self.og_from_diamond_results(fn_results)
  File "/home/........./tools/SHOOT/shoot/og_assigner.py", line 92, in og_from_diamond_results
    with gzip.open(fn_og_results_out, 'rt') as infile:
  File "/home/........./anaconda3/envs/orthofinder/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/........./anaconda3/envs/orthofinder/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'candidate_sequences.fasta.sh.ogs.txt.gz'

What is the problem?

**Comment by LDoni** [comment]
Hello @nadiak987 did you solve the problem??
L

**Comment by nkaml** [comment]
didn't really solve it but I think I ran the diamond blast manually and after that ran the script again and it worked. 
diamond blastp --db OrthoFinder/Results_xxx/diamond_profile_sequences.iqtree..d10_min20_kmeans.fa -q candidate_sequences.fa -o candidate_sequences.fa.sh.ogs.txt.gz --quiet -e 0.001 --compress  1 -p 8

**Comment by LDoni** [comment]
Thank you :)
