### ISSUE TITLE
Error No such file or directory: 'lefty1.fasta.sh.ogs.txt.gz'

### ISSUE THREAD

**Issue by jb583** [davidemms/SHOOT#9]
Hi!

I'm trying to run the following code in a shoot database I've created:

python shoot lefty1.fasta /storage/.../orthofinder/Results_Oct03    
                                                            
Traceback (most recent call last):                                                         
  File "/storage/.../miniconda3/envs/bioenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                      
    return _run_code(code, main_globals, None,
  File "/storage/.../miniconda3/envs/bioenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/storage/.../orthofinder/SHOOT/shoot/__main__.py", line 296, in <module>
    main(db, args.infile, opts)
  File "/storage/.../orthofinder/SHOOT/shoot/__main__.py", line 72, in main
    ogs, scores = og_assign.assign(fn_for_use, q_ultra_sens=opts.search_high_sens)
  File "/storage/..../orthofinder/SHOOT/shoot/og_assigner.py", line 53, in assign
    ogs, scores = self.og_from_diamond_results(fn_results)
  File "/storage/.../orthofinder/SHOOT/shoot/og_assigner.py", line 93, in og_from_diamond_results
    with gzip.open(fn_og_results_out, 'rt') as infile:
  File "/storage/.../miniconda3/envs/bioenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/storage/.../miniconda3/envs/bioenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'lefty1.fasta.sh.ogs.txt.gz'

I believe this is a similar issue to as brought up here https://github.com/davidemms/SHOOT/issues/3

My apologies I'm not familiar with Python, so I am not sure what has gone wrong here.
Many thanks in advance.

**Comment by Bokugo-Shin** [comment]
I also encountered this issue, and I realized the issue is located in the ' OGAssignDIAMOND' class in /shoot/og_assigner.py. The class initializes with incorrect database filenames that don't match the actual files generated by the database creation process.
You can replace 
```
self.profiles_db_name = "diamond_profile_sequences.fa.db.dmnd"
self.all_seqs_db_name = "diamond_all_sequences.fa.db.dmnd"
```
with
```
self.profiles_db_name = "profile_sequences.d10_min20_kmeans.fa.db.dmnd"
self.all_seqs_db_name = "profile_sequences.all.fa.db.dmnd"
```
And then, run shoot.

You can also run Diamond manually to get the * fasta.sh.ogs.txt.g file
```
diamond blastp \
  -d /path/to/OrthoFinder/Results/profile_sequences.all.fa.db.dmnd \
  -q query.fa \
  -o query.fa.sh.ogs.txt \
  --quiet \
  -e 0.001 \
  --compress 1 \
  -p 8 \
  --ultra-sensitive
```
After confirming *.fa.sh.ogs.txt.gz is generated, run shoot.

**Comment by Bokugo-Shin** [comment]
When using the `--profiles_all` to specify that SHOOT should use the full gene database, I still encountered this type of error.
Finally I found the `assign` method in 'og_assigner.py' was not passing the `q_all_seqs` parameter to the `run_diamond` method, which actually expects this parameter:
```
def run_diamond(self, fn_query, fn_out_base, q_ultra_sens=False, q_all_seqs=False):
    fn_db = self.d_db + (self.all_seqs_db_name if q_all_seqs else self.profiles_db_name)
```
Therefore, the fix is simply to add this parameter in the 'assign' method.
You can replace
```
def assign(self, infn, q_ultra_sens=False):
    fn_results = self.run_diamond(infn, fn_base, q_ultra_sens=q_ultra_sens)
```
with
```
def assign(self, infn, q_ultra_sens=False):
    fn_results = self.run_diamond(infn, fn_base, q_ultra_sens=q_ultra_sens, q_all_seqs=self.q_all_seqs_default)
```
